version: '3.12'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      DEBUG: "False"
      HOST: "0.0.0.0"
      PORT: "5000"
      MODELS_DIR: "/app/models"
      DATA_PATH: "/app/dataset.json"
      AUTO_RETRAIN: "True"
      CHECK_INTERVAL: "86400"
    volumes:
      - ./dataset.json:/app/dataset.json:ro
      - ./models:/app/models
      - ./api.log:/app/api.log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s